---
title: 'Getting and Cleaning Data: README'
author: "Chris Hartfield"
---

The purpose of this project is to demonstrate the ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis.   

One of the most exciting areas in all of data science right now is wearable computing. Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained:  

<b>Description:</b> <u>[Description](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones "Description")</u> 

The R script called run_analysis.R will do the following:
<li>Merges the training and the test sets to create one data set</li>
<li>Extracts only the measurements on the mean and standard deviation for each measurement</li>
<li>Uses descriptive activity names to name the activities in the data set</li>
<li>Appropriately labels the data set with descriptive variable names</li>
<li>Create one tidy dataset named ("tidy.data.set.1") with only the measurements on the mean and standard deviation for each measurement</li>
<li>Create one tidy dataset named ("tidy.data.set.2") with the average of each variable for each activity and each subject</li>
</br>
Below is the link for the data for the project (For the script to work you'll need to save the dataset in your R working directory): 

<b>Dataset:</b> <u>[Data](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip "Data")</u>

The code should is in the file named <b>run_analysis.R</b>
